export const WORLDS = [
  {
    id: 1,
    name: 'Grasslands',
    icon: '🌿',
    color: '#6BCB77',
    description: 'Learn to move step by step!',
    concept: 'Sequencing',
    levelRange: [1, 25],
    unlocked: true,
  },
  {
    id: 2,
    name: 'Ocean',
    icon: '🌊',
    color: '#74B9FF',
    description: 'Navigate the ocean waves!',
    concept: 'Sequencing+',
    levelRange: [26, 50],
    unlocked: false,
  },
  {
    id: 3,
    name: 'Desert',
    icon: '🏜️',
    color: '#FFD93D',
    description: 'Discover the power of loops!',
    concept: 'Loops Intro',
    levelRange: [51, 75],
    unlocked: false,
  },
  {
    id: 4,
    name: 'Forest',
    icon: '🌲',
    color: '#2ECC71',
    description: 'Master loops in the forest!',
    concept: 'Loops Mastery',
    levelRange: [76, 100],
    unlocked: false,
  },
  {
    id: 5,
    name: 'Mountains',
    icon: '⛰️',
    color: '#95A5A6',
    description: 'Make decisions on the peaks!',
    concept: 'If/Else Intro',
    levelRange: [101, 125],
    unlocked: false,
  },
  {
    id: 6,
    name: 'Space',
    icon: '🚀',
    color: '#A855F7',
    description: 'Code through the galaxy!',
    concept: 'If/Else Mastery',
    levelRange: [126, 150],
    unlocked: false,
  },
  {
    id: 7,
    name: 'Volcano',
    icon: '🌋',
    color: '#FF6348',
    description: 'Combine all your skills!',
    concept: 'Mixed Challenges',
    levelRange: [151, 175],
    unlocked: false,
  },
  {
    id: 8,
    name: 'Crystal Cave',
    icon: '💎',
    color: '#00CEC9',
    description: 'The ultimate coding adventure!',
    concept: 'Advanced',
    levelRange: [176, 200],
    unlocked: false,
  },
];
